# Generated by Django 4.2.1 on 2023-09-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_postattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default='teste', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_in_post_content',
            field=models.BooleanField(default=True, help_text=('Se marcado, exibirá a capa dentro do post',)),
        ),
    ]
