# Generated by Django 4.2.1 on 2023-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='new_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menulink',
            name='text',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menulink',
            name='url_or_path',
            field=models.CharField(default=0, max_length=2048),
            preserve_default=False,
        ),
    ]
