# Generated by Django 4.2.1 on 2023-05-20 17:06

from django.db import migrations, models
import utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0006_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favion/%Y/%m/', validators=[utils.model_validators.validate_png]),
        ),
    ]
